class Event:
    def __call__(func: function): ...

class EventManager:
    def bind(name: str): Event
    def trigger(name: str, *args, **kwargs): ...

class Peer:
    events: EventManager
    def emit(self, event: str, data: str): ...

class Network:
    events: EventManager
    def __init__(ip: str, port: int): ...
    def connect(self, ip: str, port: int): ...
    def emit(self, event: str, data: str): ...
    def tcp_connect(self, ip: str, port: int): ...
    def tcp_server(self): ...
    def udp_server(self): ...
    